CREATE TABLE APP_USERS (
  U_ID     NUMBER PRIMARY KEY,
  U_NAME   VARCHAR2(100),
  U_P      VARCHAR2(100),
  ACTV     NUMBER(1),
  CREATED_AT DATE DEFAULT SYSDATE
);


CREATE OR REPLACE TRIGGER TRG_APP_USERS
AFTER INSERT ON APP_USERS
FOR EACH ROW
BEGIN

  INSERT INTO USER1 (U_ID, U_NAME, U_P, SHOW_NAME, ACTV)
  VALUES (:NEW.U_ID, :NEW.U_NAME, :NEW.U_P, :NEW.U_NAME, :NEW.ACTV);
  
  INSERT INTO ACT_TYPE (ACT_ID, ACT_NAME, SYS_TYPE, ACT_TP, MAIN_SCRN)
  VALUES (TO_NUMBER('53' || TO_CHAR(:NEW.U_ID)), 'سند قبض'||' - '||:NEW.U_NAME, '4', 53, 'CUS_HD_DT');
    
   INSERT INTO ACT_TYPE (ACT_ID, ACT_NAME, SYS_TYPE, ACT_TP, MAIN_SCRN)
  VALUES (TO_NUMBER('57' || TO_CHAR(:NEW.U_ID)),'حوالة'||' - '||:NEW.U_NAME, '4', 57, 'CUS_HD_DT');
  
  
  --IS INSERTED BY TRIGGER INSIDE ACT_TYPE
/*  
  INSERT INTO ACT_TYPE_SCRN (ACT_ID, SYS_TYPE, SCRN, OPR)
  VALUES (TO_NUMBER('57' || TO_CHAR(:NEW.U_ID)), 4, 'CUS_HD_DT', 1);

  INSERT INTO ACT_TYPE_SCRN (ACT_ID, SYS_TYPE, SCRN, OPR)
  VALUES (TO_NUMBER('53' || TO_CHAR(:NEW.U_ID)), 4, 'CUS_HD_DT', 1);
*/

  INSERT INTO ACT_TYPE_SCRN (ACT_ID, SYS_TYPE, SCRN, OPR)
  VALUES (TO_NUMBER('57' || TO_CHAR(:NEW.U_ID)), 1, 'acc_hd_dt', 0);

  
  INSERT INTO ACT_TYPE_SCRN (ACT_ID, SYS_TYPE, SCRN, OPR)
  VALUES (TO_NUMBER('53' || TO_CHAR(:NEW.U_ID)), 1, 'acc_hd_dt', 0);

  
  INSERT INTO USER_JOURNAL (U_ID, ACT_ID, CHK)
  VALUES (:NEW.U_ID,TO_NUMBER('53' || TO_CHAR(:NEW.U_ID)), 1);

  INSERT INTO USER_JOURNAL (U_ID, ACT_ID, CHK)
  VALUES (:NEW.U_ID, TO_NUMBER('57' || TO_CHAR(:NEW.U_ID)), 1);

END;
/



  INSERT INTO APP_USERS(U_ID,U_NAME,U_P,ACTV)VALUES(23,'محسن العيسائي',23,1);

  INSERT INTO APP_USERS(U_ID,U_NAME,U_P,ACTV)VALUES(:U_ID,:U_NAME,:U_ID,1);

--الباقي
--user_cc  + user_bank  + user_account 


--act srt
--update act_type aa set aa.srl= TO_NUMBER(TO_CHAR(aa.ACT_ID)||'0000') where act_id>1000;
